'use client';

import React, { useState, useEffect } from 'react';
import { List } from 'lucide-react';
import { smoothScrollToId, generateHeadingId } from '@/utils';

interface TOCItem {
  id: string;
  text: string;
  level: number;
  element?: HTMLElement;
}

interface TableOfContentsProps {
  content: string;
}

// Set of headings to exclude from TOC
const EXCLUDED_HEADINGS = new Set(['TIMELINE']);

const TableOfContents: React.FC<TableOfContentsProps> = ({ content }) => {
  const [items, setItems] = useState<TOCItem[]>([]);
  const [isOpen, setIsOpen] = useState(false);

  // Extract headings from markdown content and sync with DOM
  useEffect(() => {
    const lines = content.split('\n');
    const tocItems: TOCItem[] = [];
    let headingIndex = 0;

    // First, extract headings from markdown
    lines.forEach((line) => {
      const trimmed = line.trim();

      // Match markdown headers: #, ##, ###
      if (trimmed.startsWith('### ')) {
        const text = trimmed
          .slice(4)
          .trim()
          .replace(/^#+\s*/, '')
          .trim();
        const id = generateHeadingId(text, headingIndex);
        tocItems.push({ id, text, level: 3 });
        headingIndex++;
      } else if (trimmed.startsWith('## ')) {
        const text = trimmed
          .slice(3)
          .trim()
          .replace(/^#+\s*/, '')
          .trim();
        const id = generateHeadingId(text, headingIndex);
        tocItems.push({ id, text, level: 2 });
        headingIndex++;
      } else if (trimmed.startsWith('# ') && !trimmed.startsWith('##')) {
        const text = trimmed
          .slice(2)
          .trim()
          .replace(/^#+\s*/, '')
          .trim();
        const id = generateHeadingId(text, headingIndex);
        tocItems.push({ id, text, level: 1 });
        headingIndex++;
      }
    });

    // Wait for DOM to render, then read actual headings
    const syncWithDOM = () => {
      const headings = Array.from(document.querySelectorAll('h1, h2, h3'));
      const domItems: TOCItem[] = [];

      // Only process headings that look like they were generated by our renderer (have an ID starting with heading-)
      // Or process all and try to match? Better to process all H1-H3 within the article

      let domHeadingIndex = 0;
      headings.forEach((heading) => {
        // Skip if it's not part of the main content (e.g. in sidebar)
        // This is a bit hacky, but usually main content headings come first or we can check parents
        // For now, let's just check if it has an ID or if we can generate one

        const level = parseInt(heading.tagName.charAt(1));
        let text = heading.textContent?.trim() || '';

        // Skip if empty or excluded
        if (!text || EXCLUDED_HEADINGS.has(text.toUpperCase())) return;

        // Remove any # symbols that might be in the text (from our renderer's anchor link)
        text = text.replace(/^#\s*/, '').trim(); // Remove leading "# " from anchor

        // Use existing ID if available (preferred)
        let id = heading.id;

        // If no ID, or if we want to ensure consistency with our markdown parser:
        if (!id) {
          // Fallback ID generation
          const cleanText = text
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/-+/g, '-')
            .replace(/^-|-$/g, '');
          id = `heading-${domHeadingIndex}-${cleanText}`;
        }

        domItems.push({ id, text, level, element: heading as HTMLElement });
        domHeadingIndex++;
      });

      // Use DOM items if available and they match roughly what we parsed
      // (length check is a simple heuristic)
      if (domItems.length > 0) {
        setItems(domItems);
      } else {
        setItems(tocItems);
      }
    };

    // Wait for content to render - reduced delay for faster TOC
    const timeoutId = setTimeout(syncWithDOM, 100);
    // Also try immediately if DOM is ready
    if (typeof window !== 'undefined' && document.readyState === 'complete') {
      syncWithDOM();
    }
    return () => clearTimeout(timeoutId);
  }, [content]);

  const scrollToHeading = (id: string) => {
    // Update URL
    history.pushState(null, '', `#${id}`);
    smoothScrollToId(id);
  };

  if (items.length === 0) return null;

  // Build hierarchical structure: h1 -> h2 -> h3
  const buildHierarchy = () => {
    type H1Node = {
      item: TOCItem;
      children: Array<{
        item: TOCItem;
        children: TOCItem[];
      }>;
    };

    type H2Node = {
      item: TOCItem;
      children: TOCItem[];
    };

    const hierarchy: H1Node[] = [];
    let currentH1: H1Node | null = null;
    let currentH2: H2Node | null = null;

    items.forEach((item) => {
      if (item.level === 1) {
        // New h1 - start a new top-level section
        currentH1 = { item, children: [] };
        currentH2 = null;
        hierarchy.push(currentH1);
      } else if (item.level === 2) {
        // New h2 - add to current h1 or create standalone if no h1
        if (currentH1) {
          currentH2 = { item, children: [] };
          currentH1.children.push(currentH2);
        } else {
          // No h1 parent, treat h2 as top-level (show as h1 equivalent)
          currentH1 = { item: { ...item, level: 1 } as TOCItem, children: [] };
          currentH2 = null;
          hierarchy.push(currentH1);
        }
      } else if (item.level === 3) {
        // New h3 - add to current h2, or current h1, or create standalone
        if (currentH2) {
          currentH2.children.push(item);
        } else if (currentH1) {
          // No h2 parent, add h3 directly to h1 (displayed at h2 indentation level)
          // Create a wrapper h2 node but keep original item for scrolling
          currentH2 = { item, children: [] };
          currentH1.children.push(currentH2);
        } else {
          // No parent, treat h3 as top-level (show as h1 equivalent)
          currentH1 = { item, children: [] };
          currentH2 = null;
          hierarchy.push(currentH1);
        }
      }
    });

    return hierarchy;
  };

  const hierarchy = buildHierarchy();

  // If no items at all, don't show TOC
  if (hierarchy.length === 0) return null;

  return (
    <div className="print:hidden">
      {/* Desktop: Right-aligned TOC - Static positioning */}
      <div className="hidden lg:block w-full">
        <div className="relative group">
          <div className="relative bg-[#0a0f14] border border-gray-800 rounded p-4 shadow-lg">
            <div className="flex items-center gap-2 text-xs font-mono text-gray-400 mb-3">
              <List size={14} />
              Contents
            </div>

            <nav className="space-y-2">
              {hierarchy.map((h1Section) => (
                <div key={h1Section.item.id} className="space-y-1">
                  {/* H1 Level */}
                  <button
                    onClick={() => scrollToHeading(h1Section.item.id)}
                    className="block w-full text-left text-xs font-mono font-bold px-2 py-1 rounded transition-colors text-white hover:text-offense hover:bg-gray-900/50"
                  >
                    {h1Section.item.text}
                  </button>

                  {/* H2 Children */}
                  {h1Section.children.map((h2Section) => (
                    <div key={h2Section.item.id} className="ml-3 space-y-0.5">
                      <button
                        onClick={() => scrollToHeading(h2Section.item.id)}
                        className="block w-full text-left text-xs font-mono px-2 py-1 rounded transition-colors text-gray-400 hover:text-offense hover:bg-gray-900/50"
                      >
                        {h2Section.item.text}
                      </button>

                      {/* H3 Children */}
                      {h2Section.children.length > 0 && (
                        <div className="ml-3 space-y-0.5 pl-2">
                          {h2Section.children.map((h3Item) => (
                            <button
                              key={h3Item.id}
                              onClick={() => scrollToHeading(h3Item.id)}
                              className="block w-full text-left text-[10px] font-mono px-2 py-0.5 rounded transition-colors text-gray-600 hover:text-offense hover:bg-gray-900/50"
                            >
                              {h3Item.text}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              ))}
            </nav>
          </div>
        </div>
      </div>

      {/* Mobile: Top of post */}
      <div className="lg:hidden mb-8">
        <div className="relative group">
          <button
            onClick={() => setIsOpen(!isOpen)}
            className="w-full flex items-center justify-between p-4 bg-[#0a0f14] border border-gray-800 rounded mb-2 transition-colors hover:border-gray-700"
          >
            <div className="flex items-center gap-2 text-xs font-mono text-gray-400">
              <List size={14} />
              TABLE OF CONTENTS
            </div>
            <div
              className={`text-gray-500 transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`}
            >
              ▼
            </div>
          </button>

          {isOpen && (
            <div className="relative bg-[#0a0f14] border border-gray-800 rounded p-4 space-y-2 max-h-64 overflow-y-auto animate-in slide-in-from-top-2 duration-200">
              <nav className="space-y-2">
                {hierarchy.map((h1Section) => (
                  <div key={h1Section.item.id} className="space-y-1">
                    {/* H1 Level */}
                    <button
                      onClick={() => {
                        scrollToHeading(h1Section.item.id);
                        setIsOpen(false);
                      }}
                      className="block w-full text-left text-xs font-mono font-bold px-2 py-1 rounded transition-colors text-white hover:text-offense hover:bg-gray-900/50"
                    >
                      {h1Section.item.text}
                    </button>

                    {/* H2 Children */}
                    {h1Section.children.map((h2Section) => (
                      <div key={h2Section.item.id} className="ml-3 space-y-0.5">
                        <button
                          onClick={() => {
                            scrollToHeading(h2Section.item.id);
                            setIsOpen(false);
                          }}
                          className="block w-full text-left text-xs font-mono px-2 py-1 rounded transition-colors text-gray-400 hover:text-white hover:bg-gray-900/50"
                        >
                          {h2Section.item.text}
                        </button>

                        {/* H3 Children */}
                        {h2Section.children.length > 0 && (
                          <div className="ml-3 space-y-0.5 pl-2">
                            {h2Section.children.map((h3Item) => (
                              <button
                                key={h3Item.id}
                                onClick={() => {
                                  scrollToHeading(h3Item.id);
                                  setIsOpen(false);
                                }}
                                className="block w-full text-left text-[10px] font-mono px-2 py-0.5 rounded transition-colors text-gray-600 hover:text-offense hover:bg-gray-900/50"
                              >
                                {h3Item.text}
                              </button>
                            ))}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                ))}
              </nav>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default TableOfContents;
